### PR TITLE
Fix #1011 - Server allows empty query

### LINKED ISSUE #1011: [Server] MissingQueryString rejection for empty query which is not required
When generating codegen-server for S3, the ListObjects operation fails with MissingQueryString rejection when no search query is specified in the uri, but it does work with empty search term (just by adding an ending `?`). 

This operation input has members with the `smithy.api#httpQuery` trait,  but none of them is required, so I don't think this should fail when the search query is missing because it is a valid request uri AFAIK.

WDYT @crisidev @david-perez 

```
$ curl -X GET http://127.0.0.1:3333/lala
Expected query string in URI but none found

$ curl -X GET http://127.0.0.1:3333/lala?
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></ListBucketResult>
```

The rejection itself originates from here:
https://github.com/awslabs/smithy-rs/blob/b828dc80feddfa23bca904ddf1f1de2cd7a6f441/codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/protocols/ServerHttpProtocolGenerator.kt#L674

### PR DESCRIPTION
**Pull request by guymguym**
## Motivation and Context
- Fix #1011 

## Description
- Avoid failing server requests on empty query.
- Temporary fix as described in https://github.com/awslabs/smithy-rs/issues/1011#issuecomment-1017394740

## Checklist

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/protocols/ServerHttpProtocolGenerator.kt [hunk 1]
```diff
@@ -746,7 +747,7 @@ private class ServerHttpProtocolImplGenerator(
         with(writer) {
             rustTemplate(
                 """
-                let query_string = request.uri().query().ok_or(#{SmithyHttpServer}::rejection::MissingQueryString)?;
```
Comment (david-perez) [inline codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/protocols/ServerHttpProtocolGenerator.kt:749]: Can you also remove the struct from `rust-runtime/aws-smithy-http-server/src/rejection.rs`? This is the only place where it was used.

Comment (guymguym) [reply codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/protocols/ServerHttpProtocolGenerator.kt:749]: Sure, done

**Review by david-perez — APPROVED** [review]
@guymguym Thank you.
