### PR TITLE
Fixes for RustWriter bugs #1465 & #1459

### LINKED ISSUE #1459: Writables string interpolation does not work with camelcase identifiers
Let's say we have a writable like this one:

```kotlin
fun renderObject(): Writable =
    writable {
        rust("""let mystring = String::from("Weeeeeeeee");""");
    }
```

The writable can be interpolated in any `rustTemplate` like this:

```kotlin
rustTemplate("#{myobject:W}", "myobject" to renderObject())
```

If I setup the context using a camelcase identifier (IE `myObject` instead of `myobject`), it results in a Kotlin stacktrace:

```
Projection pokemon_service_sdk failed: java.lang.NullPointerException: Parameter specified as non-null is null: method software.amazon.smithy.rust.codegen.rustlang.RustWriter$RustWriteableInjector.apply, parameter t
software.amazon.smithy.rust.codegen.rustlang.RustWriter$RustWriteableInjector.apply(RustWriter.kt)
software.amazon.smithy.rust.codegen.rustlang.RustWriter$RustWriteableInjector.apply(RustWriter.kt:516)
software.amazon.smithy.utils.AbstractCodeWriter.applyFormatter(AbstractCodeWriter.java:1861)
software.amazon.smithy.utils.CodeFormatter$Operation.lambda$formatted$1(CodeFormatter.java:108)
software.amazon.smithy.utils.CodeFormatter$BlockOperation$Unconditional.apply(CodeFormatter.java:228)
software.amazon.smithy.utils.CodeFormatter.run(CodeFormatter.java:41)
software.amazon.smithy.utils.AbstractCodeWriter.format(AbstractCodeWriter.java:1596)
software.amazon.smithy.utils.AbstractCodeWriter.write(AbstractCodeWriter.java:1652)
software.amazon.smithy.rust.codegen.rustlang.RustWriter.write(RustWriter.kt:363)
software.amazon.smithy.rust.codegen.rustlang.RustWriterKt$rustTemplate$1.invoke(RustWriter.kt:189)
software.amazon.smithy.rust.codegen.rustlang.RustWriterKt$rustTemplate$1.invoke(RustWriter.kt:188)
software.amazon.smithy.rust.codegen.rustlang.RustWriterKt.withTemplate(RustWriter.kt:91)
software.amazon.smithy.rust.codegen.rustlang.RustWriterKt.rustTemplate(RustWriter.kt:188)
software.amazon.smithy.rust.codegen.server.python.smithy.generators.PythonServerEnumGenerator.renderPyO3Methods(PythonServerEnumGenerator.kt:56)
software.amazon.smithy.rust.codegen.server.python.smithy.generators.PythonServerEnumGenerator.render(PythonServerEnumGenerator.kt:46)
software.amazon.smithy.rust.codegen.server.python.smithy.PythonServerCodegenVisitor$stringShape$1$1.invoke(PythonServerCodegenVisitor.kt:163)
software.amazon.smithy.rust.codegen.server.python.smithy.PythonServerCodegenVisitor$stringShape$1$1.invoke(PythonServerCodegenVisitor.kt:162)
software.amazon.smithy.rust.codegen.smithy.RustCrate.useShapeWriter$lambda-0(CodegenDelegator.kt:60)
software.amazon.smithy.codegen.core.WriterDelegator.useShapeWriter(WriterDelegator.java:208)
software.amazon.smithy.rust.codegen.smithy.RustCrate.useShapeWriter(CodegenDelegator.kt:60)
software.amazon.smithy.rust.codegen.server.python.smithy.PythonServerCodegenVisitor.stringShape(PythonServerCodegenVisitor.kt:162)
software.amazon.smithy.rust.codegen.server.python.smithy.PythonServerCodegenVisitor.stringShape(PythonServerCodegenVisitor.kt:42)
software.amazon.smithy.model.shapes.StringShape.accept(StringShape.java:41)
software.amazon.smithy.rust.codegen.server.python.smithy.PythonServerCodegenVisitor.execute(PythonServerCodegenVisitor.kt:105)
software.amazon.smithy.rust.codegen.server.python.smithy.PythonCodegenServerPlugin.execute(PythonCodegenServerPlugin.kt:47)
software.amazon.smithy.build.SmithyBuildImpl.applyPlugin(SmithyBuildImpl.java:397)
software.amazon.smithy.build.SmithyBuildImpl.applyProjection(SmithyBuildImpl.java:328)
software.amazon.smithy.build.SmithyBuildImpl.executeSerialProjection(SmithyBuildImpl.java:224)
software.amazon.smithy.build.SmithyBuildImpl.lambda$applyAllProjections$5(SmithyBuildImpl.java:189)
java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### LINKED ISSUE #1465: `Attribute.Custom.render()` is stripping comment line chars `//`
I am facing a weird issue with the `Attribute` class:

I am trying to render a `Custom` attribute before structures and enums and if there is a comment line rendered just after my call to `Attribute.Custom.render()`, the `//` is eaten away. 

I have tracked it down to this line of code: https://github.com/awslabs/smithy-rs/blob/15e1b3425f56ff2606121e99dff11de38424c744/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/rustlang/RustTypes.kt#L377

If I change the line from writer.raw("#$bang[$annotation]") to writer.rust("##$bang[$annotation]") it start rendering as I would expect, but I am not sure of the implications of changing this line of code.

### PR DESCRIPTION
**Pull request by rcoh**
## Motivation and Context
- Fixes #1465
- Fixes #1459 

## Description
Fix for two longstanding RustWriter bugs:
1. `docs` didn't call `ensureNewLine()` which meant that when it was invoked after a call to `writeInline` the leading `///` was never written
2. formatting with `:W` didn't go through template rewriting which meant that it didn't work with case sensitivity.

This resolves both of those issues and adds unit tests.
## Testing
- unit test
## Checklist

- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates
- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the AWS SDK, generated SDK code, or SDK runtime crates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by Velfi — APPROVED** [review]

**Comment by rcoh** [comment]
oh hmm...looking at the generated code diff, this adds extra newlines

File: codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/rustlang/RustWriter.kt [hunk 1]
```diff
@@ -259,6 +260,9 @@ fun <T : AbstractCodeWriter<T>> T.docs(text: String, vararg args: Any, newlinePr
             // Rustdoc warns on tabs in documentation
             it.trimStart().replace("\t", "  ")
         }
+    // Because writing docs relies on the newline prefix, ensure that there was a new line written
+    // before we write the docs
+    this.ensureNewline()
```
Comment (crisidev) [inline codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/rustlang/RustWriter.kt:265]: I was looking into this from a completely wrong angle..
