### PR TITLE
fix(codegen): Fix bug triggered by operation input/output naming

### LINKED ISSUE #662: Synthetic input/output shapes are overwriting operations in the Smithy model
When smithy-rs creates synthetic inputs/outputs in `OperationNormalizer`, it is sometimes overwriting operations that happen to have the same name. For example, in `kinesisanalytics`, there are two operations named `DeleteApplication` and `DeleteApplicationOutput`. When we create the synthetic output for `DeleteApplication`, it is named `DeleteApplicationOutput`, and since the model is a map of shape id to shape, the operation of the same name is completely replaced by the synthetic output.

### PR DESCRIPTION
**Pull request by rcoh**
-[ ] Tier-2 check passed
- Fixes #662 
## Motivation and Context
During codegeneration, synthetic copies of input & output shapes are created. However, due to a Smithy shape id conflict, these
shapes were overwriting existing shapes in the model instead of creating new shapes.

## Description
This lead to a number of bugs exposed by the new s3control model. A minimal example of this model is included as a test in rest-xml-extras.

This commit augments the namespace of synthetic shapes to exist in the `synthetic` Smithy namespace, removing the conflict. After this bug was fixed, a subsequent bug in the serializer function naming was exposed where two shapes with the same name but in different modules generated a conflicting serializer.

## Testing

Tests:
- [x] new s3control model compiles
- [x] test case added to rest-xml-extras

## Checklist
- [x] I have updated `CHANGELOG.md`
- [x] I have updated `aws/SDK_CHANGELOG.md` if applicable

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by Velfi — APPROVED** [review]

File: codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/transformers/OperationNormalizer.kt [hunk 1]
```diff
@@ -37,6 +40,10 @@ object OperationNormalizer {
             // Generate or modify the input and output of the given `Operation` to be a unique shape
             syntheticInputShapes(model, operation) + syntheticOutputShapes(model, operation)
         }
+        val shapeConflict = newShapes.firstOrNull() { shape -> model.getShape(shape.id).isPresent }
+        check(
+            shapeConflict == null
+        ) { "shape $shapeConflict conflicted with an existing shape in the model (${model.getShape(shapeConflict!!.id)}. This is a bug." }
```
Comment (Velfi) [inline codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/transformers/OperationNormalizer.kt:46]: I love that this message calls the error out as the result of a bug

**Comment by jdisanti** [comment]
I think this fixes #662. I'm curious how you avoided the instantiator failures. I wonder if it works since it's a nested namespace rather than a completely disjoint namespace?

Should also clean this up: https://github.com/awslabs/smithy-rs/blob/3b8f69c18db227f99ea8b458324f4e2ed3daddf4/codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/util/Smithy.kt#L71-L76

**Comment by rcoh** [comment]
I think that #662 didn't fix it because in the codegen unit tests, we actually load the entire service closure all at once from multiple services and the lack of nested namespacing caused collisions.
