### PR TITLE
Fix signing of UTF-8 header values

### LINKED ISSUE #708: aws-sigv4 must support non-ascii header values
See https://github.com/awslabs/aws-sdk-rust/issues/226

### PR DESCRIPTION
**Pull request by jdisanti**
## Motivation and Context
This fixes #708 and will fix aws-sdk-rust#226 upon release.

## Testing
- Added a unit test that reproduced the issue
- Manually tested by calling S3 PutObject with metadata that had non-ASCII characters

## Checklist
- [ ] I have updated `CHANGELOG.md`
- [x] I have updated `aws/SDK_CHANGELOG.md` if applicable

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: aws/rust-runtime/aws-sigv4/src/http_request/canonical_request.rs [hunk 1]
```diff
@@ -317,7 +317,12 @@ impl<'a> fmt::Display for CanonicalRequest<'a> {
             // a missing header is a bug, so we should panic.
             let value = &self.headers[&header.0];
             write!(f, "{}:", header.0.as_str())?;
-            writeln!(f, "{}", value.to_str().unwrap())?;
+            writeln!(
```
Comment (jdisanti) [inline aws/rust-runtime/aws-sigv4/src/http_request/canonical_request.rs:320]: I wonder if we should just use the header value's bytes in the canonical request. Although, doing so would require some refactoring of the sigv4 crate since it wouldn't be able to use the `Display` trait anymore for formatting this since the bytes could be invalid UTF-8.

Comment (rcoh) [reply aws/rust-runtime/aws-sigv4/src/http_request/canonical_request.rs:320]: I don't think it's possible from smithy to ever put non-utf8 encoded data into a header value, IIRC. So this should be enough.

File: aws/rust-runtime/aws-sigv4/src/http_request/canonical_request.rs [hunk 2]
```diff
@@ -317,7 +317,12 @@ impl<'a> fmt::Display for CanonicalRequest<'a> {
...
+                f,
+                "{}",
+                std::str::from_utf8(value.as_bytes())
```
Comment (rcoh) [inline aws/rust-runtime/aws-sigv4/src/http_request/canonical_request.rs:323]: can signing fail? It would be _much_ better to fail with a result than to panic here

**Review by rcoh — APPROVED** [review]
approved for getting a fix out, but we should probably avoid a panic in this situation

File: aws/rust-runtime/aws-sigv4/src/http_request/canonical_request.rs (hunk 2 above)
Comment (jdisanti) [reply aws/rust-runtime/aws-sigv4/src/http_request/canonical_request.rs:323]: Tracking in #711.
