### PR TITLE
Fix precision issue with RFC-3339 timestamp serialization

### LINKED ISSUE #478: Losing precision on RFC-3339 timestamps
The RFC-3339 timestamp formatter implementation in `smithy-types` is removing trailing `0` characters to get rid of subsecond nanos, but this can result in the last zero in the seconds place being truncated. For example, `1969-12-31T18:22:50Z` can erroneously become `1969-12-31T18:22:5Z`.

### PR DESCRIPTION
**Pull request by jdisanti**
Fixes #478 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: rust-runtime/smithy-types/src/instant/format.rs [hunk 1]
```diff
@@ -418,4 +419,152 @@ pub mod iso_8601 {
...
+        );
+        assert_eq!(
+            "0001-05-06T02:15:00Z",
+            format(&Instant::from_epoch_seconds(-62124788700))
+        );
+        assert_eq!(
+            "+33658-09-27T01:46:40Z",
+            format(&Instant::from_epoch_seconds(1_000_000_000_000))
+        );
+        assert_eq!(
```
Comment (rcoh) [inline rust-runtime/smithy-types/src/instant/format.rs:502]: lol glad we are future proofing this

**Review by rcoh — APPROVED** [review]
