### PR TITLE
Make `RustReservedWordsSymbolProvider` configurable

### LINKED ISSUE #1766: Split `RustReservedWords` into composed classes
It needs to be broken up into multiple composed classes since right now it has client-specific logic in it to handle the `Unknown` enum variants.

See https://github.com/awslabs/smithy-rs/pull/1762#discussion_r978154319.

### PR DESCRIPTION
**Pull request by jdisanti**
## Motivation and Context
Fixes #1766.

## Checklist
- [x] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by Velfi — APPROVED** [review]

File: codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/ClientReservedWords.kt [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+        ),
+    unionMemberMap = mapOf(
+        // Unions contain an `Unknown` variant. This exists to support parsing data returned from the server
+        // that represent union variants that have been added since this SDK was generated.
+        UnionGenerator.UnknownVariantName to "${UnionGenerator.UnknownVariantName}Value",
+        "${UnionGenerator.UnknownVariantName}Value" to "${UnionGenerator.UnknownVariantName}Value_",
+    ),
+    enumMemberMap = mapOf(
+        // Unknown is used as the name of the variant containing unexpected values
+        "Unknown" to "UnknownValue",
```
Comment (jdisanti) [inline codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/ClientReservedWords.kt:31]: From a comment on #2377, these should have constants.

**Review by ysaito1001 — APPROVED** [review]

**Review by hlbarber — COMMENTED** [review]
Is the change from `send` to `send_value` shown in the [Server Test](https://d2luzm2xt3nokh.cloudfront.net/codegen-diff/3337f935d6602265d989039b20b203f59a17b53d/4f5907602eba24222978253eaa4414587a97a6c3/server-test/index.html) intended?

It looks like we've lost this mapping 
```kotlin
                "build" -> "build_value"
                "builder" -> "builder_value"
                "default" -> "default_value"
                "send" -> "send_value"
                // To avoid conflicts with the `make_operation` and `presigned` functions on generated inputs
                "make_operation" -> "make_operation_value"
                "presigned" -> "presigned_value"
                "customize" -> "customize_value"
                // To avoid conflicts with the error metadata `meta` field
                "meta" -> "meta_value"

```

on the server side, and it's been restored for the client side only?

**Comment by jdisanti** [comment]
> Is the change from send to send_value shown in the [Server Test](https://d2luzm2xt3nokh.cloudfront.net/codegen-diff/3337f935d6602265d989039b20b203f59a17b53d/4f5907602eba24222978253eaa4414587a97a6c3/server-test/index.html) intended?

Does `send` need to be reserved on the server side? My thinking on this was that `send` is reserved on the client side due to us adding a `send()` function to fluent builders to actually send a request, but that seems unnecessary on the server side.

Good catch though, I need to add a `breaking-change` label to this PR.

File: codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/ClientReservedWords.kt [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+ */
+
+package software.amazon.smithy.rust.codegen.client.smithy
+
+import software.amazon.smithy.rust.codegen.core.rustlang.RustReservedWordConfig
+import software.amazon.smithy.rust.codegen.core.smithy.generators.StructureGenerator
+import software.amazon.smithy.rust.codegen.core.smithy.generators.UnionGenerator
+
+val ClientReservedWords = RustReservedWordConfig(
+    structMemberMap = StructureGenerator.structMemberMap +
```
Comment (david-perez) [inline codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/ClientReservedWords.kt:13]: nit: I consciously make the effort to use "structure" to refer to Smithy structure shapes, and use struct only to refer to Rust `struct`s.

File: codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/RustReservedWords.kt [hunk 3]
```diff
@@ -33,34 +44,19 @@ class RustReservedWordSymbolProvider(private val base: RustSymbolProvider) : Wra
...
-                "make_operation" -> "make_operation_value"
-                "presigned" -> "presigned_value"
-                "customize" -> "customize_value"
-                // To avoid conflicts with the error metadata `meta` field
-                "meta" -> "meta_value"
-                else -> reservedWordReplacedName
+            container is StructureShape -> when (val mapped = reservedWordConfig.structMemberMap[baseName]) {
+                null -> reservedWordReplacedName
+                else -> mapped
             }
```
Comment (david-perez) [inline codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/RustReservedWords.kt:50]:
```suggestion
            container is StructureShape ->
                reservedWordConfig.structMemberMap.getOrDefault(baseName, reservedWordReplacedName)
```

These can be slightly simplified.

File: codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/RustReservedWords.kt [hunk 4]
```diff
@@ -33,34 +44,19 @@ class RustReservedWordSymbolProvider(private val base: RustSymbolProvider) : Wra
...
 
-            container is EnumShape || container.hasTrait<EnumTrait>() -> when (baseName) {
-                // Unknown is used as the name of the variant containing unexpected values
-                "Unknown" -> "UnknownValue"
-                // Real models won't end in `_` so it's safe to stop here
-                "UnknownValue" -> "UnknownValue_"
-                else -> reservedWordReplacedName
+            container is EnumShape || container.hasTrait<EnumTrait>() -> when (val mapped = reservedWordConfig.enumMemberMap[baseName]) {
```
Comment (david-perez) [inline codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/RustReservedWords.kt:57]: `EnumTrait` is only applicable to string shapes; a member shape's container cannot be a string shape.
```suggestion
            container is EnumShape -> when (val mapped = reservedWordConfig.enumMemberMap[baseName]) {
```

File: codegen-core/src/test/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/RustReservedWordsTest.kt [hunk 5]
```diff
@@ -22,18 +22,108 @@ import software.amazon.smithy.rust.codegen.core.util.lookup
 internal class RustReservedWordSymbolProviderTest {
```
Comment (david-perez) [inline codegen-core/src/test/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/RustReservedWordsTest.kt:22]: Great tests.

**Review by david-perez — APPROVED** [review]
The list of server reserved words looks good.

File: codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/RustReservedWords.kt (hunk 4 above)
Comment (jdisanti) [reply codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/rustlang/RustReservedWords.kt:57]: Hmmm... Yeah, I think this is dead code. `toMemberName` isn't even called for enum rendering. I think I'll keep it around in the event that someone refactors EnumGenerator to use `toMemberName` though since this is technically correct.
